### ISSUE TITLE
Arrivals ignoring altitude restrictions

### ISSUE THREAD

**Issue by Fechulo** [openscope/openscope#1045]
Browser: Chrome

Airport: KBOS

#### Issue Description
Despite the altitude restrictions on the STARs, aircraft are descending to the final altitude, well outside the airspace
![low altitude](https://user-images.githubusercontent.com/13125311/43717835-aacb026a-9980-11e8-9153-e2569f9ca06b.PNG)
In the picture, we can see JBU3864 at 5,000ft aproaching `PROVI` which has a restriction of at or above 11,000ft

**Comment by felixscheffer** [comment]
```
_calculateTargetedAltitudeVnavDescent(waypointWithMaximumAltitudeRestriction) {
    const waypointMaximumAltitude = waypointWithMaximumAltitudeRestriction.altitudeMaximum;

    if (!this.isBeyondTopOfDescentForWaypointModel(waypointWithMaximumAltitudeRestriction)) {
        return;
    }

    return Math.min(waypointMaximumAltitude, this.mcp.altitude);
}
```
`this.mcp.altitude` is set to 5,000ft by `initializeForAirborneFlight()`. Because of `Math.min(waypointMaximumAltitude, this.mcp.altitude)` the waypoint's altitude restriction is ignored and the aircraft is descending straight down to  5,000ft.

To make things worse `_calculateTargetedAltitudeVnavClimb()` is suffering from the same issue, so instead of climbing aircrafts to the waypoint's mimimal altitude, it will actually descend the aircrafts to 5000ft.

Some aircrafts are spawned below the minimal altitude of the first waypoint. Spawned at 17,800ft vs RUIZE minimal 21,000ft. As a result the code (rightly) calls `_calculateTargetedAltitudeVnavClimb()` but because of the behavior mentioned above the aircraft will descend to 5,000ft instead of climbing to 21,000ft.
