### ISSUE TITLE
Aircraft pre-spawning within the airspace

### ISSUE THREAD

**Issue by indianbhaji** [openscope/openscope#1046]
Browser: Chrome

Airport: EDDF/[LTBA](https://github.com/openscope/openscope/pull/936)/[LROP](https://github.com/openscope/openscope/pull/336)

Approximate play time before issue: 0 minutes

#### Issue Description
Aircraft pre-spawn within the airspace when the airport loads.

**Comment by indianbhaji** [comment]
Reproduceable on [LROP](https://github.com/openscope/openscope/pull/336) too

**Comment by erikquinn** [comment]
desired behavior.

**Comment by cake-pie** [comment]
I thought desired behavior for prespawning is to have some arrivals start *just outside of airspace boundaries* so they begin arriving into the airspace soon after initial airport load (rather than have to wait from them to make their way from the usual faraway spawn positions).

But OP seems to describe arrivals *already within* the airspace right from the start.

Anyhow, I wasn't able to replicate on EDDF/LTBA/LROP on 6.22 so @indianbhaji can perhaps clarify and reopen if this is still a problem.

**Comment by erikquinn** [comment]
It may be a bug in the logic, but the result is perfectly fine (and arguably, _desirable_). It's also possible that it is intended to do this. Either way, it doesn't pose any negative effect to the user.
