### ISSUE TITLE
Subtask: Distance based sep for same-rwy departures

### ISSUE THREAD

**Issue by felixscheffer** [openscope/openscope#1232]
epic openscope/openscope#12

**Comment by erikquinn** [comment]
For the same runway, basic separation depends on the `srs` value of the aircraft (already present in the json).
- Trailing ac is category 1: 3000 feet
- Trailing ac is category 2: 4500 feet
- When either is category 3: 6000 feet

Aircraft operating on the same runway must comply with the above separation values, with only one aircraft on the ground with a landing/takeoff clearance at a given time.

For example, a category 3 departs, and another category 3 is ready. The second can not be cleared until the first is 6000 feet down the runway _and off the ground_.

If a category 3 is cleared to land, and another category 3 is cleared for takeoff, the departure must be 6000 feet down the runway _and off the ground_ before the arrival crosses the runway threshold (we can use the approachOffset to determine this).

---

Separately, if you're looking to do wake turbulence (what the epic issue is about), there are timed rules:
- If a 757, heavy, or super aircraft departs the "same runway", full length, where any other aircraft wishes to depart _full length_, they cannot be cleared until two minutes _from the time the aircraft began their departure roll_ (we can use the time of the clearance). If the first aircraft is more than 5 miles away from the first, they are separated, regardless of the timer.
- If a Large (or larger) aircraft departs the "same runway", where a small aircraft wishes to depart from an intersection beyond the point where the first was cleared, they cannot be cleared until three minutes _from the time the first aircraft rotated (this is moot, since we don't do intersection departures)
- Wake turbulence separation for arrivals is not provided by tower, but rather by the approach control.

Note: For wake turbulence, runways whose centerlines are within 2500 feet are considered the same runway in terms of applying wake turbulence separation.

**Comment by felixscheffer** [comment]
@erikquinn Are all aircrafts supposed to have an `srs` value? Because we have aircrafts for which `srs` is null.

**Comment by erikquinn** [comment]
Yes, they are all supposed to have it, if it exists. Super obscure aircraft may not be assigned one, and in those cases, null is probably okay. We would just apply the max separation value (6000).
