### ISSUE TITLE
A/C taxing to non-existent runway

### ISSUE THREAD

**Issue by wmstapp** [openscope/openscope#1280]
Browser: Chrome

Airport: KMIA

Approximate play time before issue: 30 Mins

#### Issue Description
Taxi AC to RWY 12.  AC showed up in middle of airport, When given the TO command, the AC proceeds to TO at an apparent 360* heading and error received that AC took off with tail wind.  Was with ENY5044 and AC type was E170.

#### Steps to reproduce
-

**Comment by cake-pie** [comment]
Just encountered this at KBOS. Arrivals 22L, departures 22R.
DAL670 filed `CELTK5 CELTK FRILL` was issued `caf cvs w 22r` and `pd celtk + 475 to` but took off in a northerly direction with tail wind warning, and into the path of oncoming arrivals.

![22r](https://user-images.githubusercontent.com/28502722/53807041-840c9f80-3f89-11e9-8af2-0e693bdd7e89.png)

Screencap is after the tail wind message had already faded out -- lost a few seconds being confused before realizing that bug had occurred.

Ignoring the arrival JBU on 22L it is possible to discern that acft probably originated from middle of airport as was also observed by OP.

After some more fumbling with dev tools I was able to pause script execution and locate the `AircraftModel` data for the acft:

* [screencap from console](https://user-images.githubusercontent.com/28502722/53807646-0a75b100-3f8b-11e9-93fb-0d418ab8db0b.png) expanded to hopefully show most of the pertinent data  
(Warning: 1440x4735px png)
* [full JSON](https://github.com/openscope/openscope/files/2931055/DAL607-rwy22R.zip) captured using [console.save](https://bgrins.github.io/devtools-snippets/#console-save) and [json-stringify-safe](https://github.com/moll/json-stringify-safe)  
(77 MB)

I too am clueless re: steps to reproduce, but hopefully the JSON dump could reveal something.

**Comment by cake-pie** [comment]
Same as above, KBOS, arrivals on 22L, departures on 22R
JBU5613 decides that runways are optional: [1](https://user-images.githubusercontent.com/28502722/54678673-96b5d580-4b40-11e9-89fd-a7d90ae542c9.png) [2](https://user-images.githubusercontent.com/28502722/54678674-96b5d580-4b40-11e9-8234-831c13c4e439.png)

**Comment by felixscheffer** [comment]
@cake-pie  Have you been able to figure out what causes the issue?

**Comment by cake-pie** [comment]
No clue, seems pretty random.

**Comment by cake-pie** [comment]
Likely suspect is as per @felixscheffer described in [#872 (comment)](https://github.com/openscope/openscope/pull/872#issuecomment-415768047):

> we are setting FLIGHT_PHASE.WAITING twice.
> 
> 1. in `_changeFromTaxiToWaiting()` which is triggered by `GameController.game_timeout` in `taxiToRunway()`
> 2. in `updateFlightPhase` after `taxi_time` has elapsed

[The latter](https://github.com/openscope/openscope/blob/05461edcf881b6eb2f0ae3c202791ae4804e8750/src/assets/scripts/client/aircraft/AircraftModel.js#L1546-L1555) was the original pre-exisitng state-machine type implementation, routinely called from `update`. It checks if time elapsed since taxi start exceeds taxi time, i.e. the aircraft has arrived at the rwy hold and thus joined the queue. When the criteria is satisfied, the flight phase is changed and `moveToRunway` is called to set aircraft's position/hdg/alt appropriately per departure runway:
```
case FLIGHT_PHASE.TAXI: {
    const elapsed = TimeKeeper.accumulatedDeltaTime - this.taxi_start;

    if (elapsed > this.taxi_time) {
        this.setFlightPhase(FLIGHT_PHASE.WAITING);
        this.moveToRunway(runwayModel);   // departure runway
    }

    break;
}
```

The former was added in #872; [`taxiToRunway`](https://github.com/openscope/openscope/blob/05461edcf881b6eb2f0ae3c202791ae4804e8750/src/assets/scripts/client/aircraft/AircraftModel.js#L1336-L1341) sets a timer to call `_changeFromTaxiToWaiting` upon expiry of taxi time:
```
GameController.game_timeout(
    this._changeFromTaxiToWaiting,
    this.taxi_time,
    this,
    null
);
```
... and [that](https://github.com/openscope/openscope/blob/05461edcf881b6eb2f0ae3c202791ae4804e8750/src/assets/scripts/client/aircraft/AircraftModel.js#L1354-L1356) in turn only changes the flight phase *without* setting aircraft position/hdg/alt to correspond to runway:
```
_changeFromTaxiToWaiting() {
    this.setFlightPhase(FLIGHT_PHASE.WAITING);
}
```

Both mechanisms are competing to see which gets to set FLIGHT_PHASE.WAITING first.

If `_changeFromTaxiToWaiting` acts first, then `updateFlightPhase` will not run, and since aircraft pos/hdg/alt has not been set, it appears at the "middle" of the airport at a heading of 360. This seems to occur by pure chance and is very rare, but we can replicate the behavior of the bug by artificially messing with the timing:
```
GameController.game_timeout(
    this._changeFromTaxiToWaiting,
    this.taxi_time-1,
    ...
```

Conversely, usually `updateFlightPhase` acts first, and `_changeFromTaxiToWaiting` afterward, generally with no noticable impact. However, it is theoretically possble for a takeoff order to be issued to the aircraft after `updateFlightPhase` but before `_changeFromTaxiToWaiting` in which case it will be erroneously switched from FLIGHT_PHASE.TAKEOFF back to FLIGHT_PHASE.WAITING again. That likely breaks the simulation, with the aircraft becoming stationary (since it is WAITING) but invisible on scope (not first in queue at a runway) and will just sit there causing separation penalties.

The `GameController.game_timeout` mechanism is redundant and can be safely removed.

**Comment by n8rzz** [comment]
good find and excellent write up!

**Comment by erikquinn** [comment]
Wow. Brilliant investigative work indeed!!! @cake-pie
