### ISSUE TITLE
Render all map layers for airport

### ISSUE THREAD

**Issue by oobayly** [openscope/openscope#1436]
Currently, the maps object in the aiports file has implicit support for multiple "layers", but the `CanvasController` only renders the `base` layer.

It's a trivial change to iterate through all the layers and render each of them on the canvas. The benefit for doing this is that if part of the videomap is updated, diffs will be a little less overwhelming.
``` js
for (let mapKey in airportModel.maps) {
    const mapList = airportModel.maps[mapKey];
    if (!mapList || !mapList.length) {
        continue;
    }
    for (let i = 0; i < mapList.length; i++) {
        const mapItem = mapList[i];
        cc.moveTo(
            CanvasStageModel.translateKilometersToPixels(mapItem[0]),
            -CanvasStageModel.translateKilometersToPixels(mapItem[1])
        );
        cc.lineTo(
            CanvasStageModel.translateKilometersToPixels(mapItem[2]),
            -CanvasStageModel.translateKilometersToPixels(mapItem[3])
        );
    }
}
```

However, while this is the simplest method, is it the best? For a bit of future proofing It could be preferable to format the layer similarly to the restricted values:
``` json
"maps": {
  "base": {
    "name": "Base Map",
    "lines": [
      ["51.0", "-10.0", "53.0", "-8"]
    ]
  },
  "centrelines": {
    "name": "Extended Centrelines",
    "lines": [
      ["51.0", "-10.0", "53.0", "-8"]
    ]
  },
  "coastline": {
    "name": "Coastlines",
    "lines": [
      ["51.0", "-10.0", "53.0", "-8"]
    ]
  }
}
```
This way, if desired in the future the UI would be able to specify which layers to display, along with friendly names. Again, it would be relatively trivial to refactor all the existing airports to use this type schema, although it might break tools that people may have used.

**Comment by Fechulo** [comment]
I don't think many tools have been made for the creation of video maps, since the vast majority of the time all that's required is to copy and paste from existing files. In the few cases where this isn't possible, it is done manually without the aid of any automated tools. Giving each one a name would also allows us to eventually have different video maps for different runway configurations, which would be awesome.

**Comment by erikquinn** [comment]
Definitely a good start, though I think I would go for a very slightly different implementation here. There's no real need to have a technical name, eg `centerlines`, separate from an english name, eg `Extended Centerlines`, and I'd also like to get away from using `base` at all. The maps should be named for what they are (could be `base map` or something, but the point is that its not required to have a map by that name). And then the airport file will determine which map(s) should be shown by default.


```javascript
"defaultMaps": ["East Ops", "Satellite"],

...
...
...

"maps": {
  "East Ops": [
    ["51.0", "-15.0", "51.0", "-8"],
    ["50.0", "-12.0", "52.0", "-9.1"],
    ["52.0", "-14.0", "53.0", "-10"],
    ["55.0", "-10.0", "54.0", "-8"]
  ],
  "West Ops": [
    ["51.0", "-15.0", "51.0", "-8"],
    ["50.0", "-12.0", "52.0", "-9.1"],
    ["52.0", "-14.0", "53.0", "-10"],
    ["55.0", "-10.0", "54.0", "-8"]
  ],
  "Satellite": [
    ["51.0", "-15.0", "51.0", "-8"],
    ["50.0", "-12.0", "52.0", "-9.1"],
    ["52.0", "-14.0", "53.0", "-10"],
    ["55.0", "-10.0", "54.0", "-8"]
  ],
}
```

For me, the only potentially difficult part of this problem is how to provide the ability to turn maps on/off. The way I see it working is by the buttons along the command bar having sub-menus which expand upward-- for example, you click on a video maps button, and if there are 5 maps, there are 5 buttons which appear directly above the video maps button, each labeled with their name. Users could then toggle the desired maps, and close the submenu by clicking the video maps button again when they are done. For plans on this and consolidating the menu buttons, see #1191.

**Comment by n8rzz** [comment]
>The benefit for doing this is that if part of the videomap is updated, diffs will be a little less overwhelming

This is mostly true, however, the canvas itself is actually two canvases.  We've already broken up the continuous renders (data blocks, aircraft, etc) and the others (terrain, video maps, fixes, etc).  With this in mind, I still think this would be good to do.  Some video maps are a little busy, so having the ability to toggle parts of it on and off would, I think, be a popular feature and definitely very useful!

_Small nitpick: I'd discourage the use of spaces in key names._

**Comment by erikquinn** [comment]
> Small nitpick: I'd discourage the use of spaces in key names.

I generally agree, but thought there was an advantage to being able to use the key name as the english name so you can display it directly and reference it using the english name in the `defaultMaps` key. We can certainly do like `"maps": { "east-ops": { name: "East Ops", "lines": [] } },` type thing if that's more desirable. It just seemed cleaner and easier to put the english in the key.

In fact, if we do want to go that route, we don't really need a key at all, we can just filter by the english name if it's a simple array of objects with their own name properties rather than using keys at all:

```javascript
"defaultMaps": ["East Ops", "Satellite"],

...
...
...

"maps": [
  {
    name: "East Ops",
    lines: [
      ["51.0", "-15.0", "51.0", "-8"],
      ["50.0", "-12.0", "52.0", "-9.1"],
      ["52.0", "-14.0", "53.0", "-10"],
      ["55.0", "-10.0", "54.0", "-8"]
    ]
  },  
  {
    name: "West Ops",
    lines: [
      ["51.0", "-15.0", "51.0", "-8"],
      ["50.0", "-12.0", "52.0", "-9.1"],
      ["52.0", "-14.0", "53.0", "-10"],
      ["55.0", "-10.0", "54.0", "-8"]
    ]
  },
  {
    name: "Satellite",
    lines: [
      ["51.0", "-15.0", "51.0", "-8"],
      ["50.0", "-12.0", "52.0", "-9.1"],
      ["52.0", "-14.0", "53.0", "-10"],
      ["55.0", "-10.0", "54.0", "-8"]
    ]
  }
]
```

**Comment by n8rzz** [comment]
the couple issues you run into with strings and spaces as key names are, mainly, the following:
```js
const obj = {
  // key must always be quoted. not an issue with json, but is abnormal in js objects
  'key with spaces': null,
  keyWithoutSpaces: null
};

// accessing
const value = obj['key with spaces'];
const value = obj.keyWithSpaces;
```

The differences are not major, but there are differences and those differences can lead to inconsistencies in the code.

**Comment by oobayly** [comment]
Yup, that was my thought to. I have to admit, I've never an instance where I've had keys with spaces. It also means that if you ever want localisation (yes, ATC is generally English, but...) in the future refactoring keys isn't required. I've created a local branch to test a couple of airports (distinct keys and names) and so far it hasn't blown up!

**Comment by erikquinn** [comment]
All makes sense. We won't ever need to access a specific map explicitly in the code, eg `maps['East Ops']`; it would only be accessed by passing the name in a variable, eg `maps[mapName]`.

If it's too unnatural to see it with the spaces, we can certainly go with the array of objects for maps instead, just preferably not an object of objects.

**Comment by oobayly** [comment]
So, I went with the array of object option:
* Add `MapLayerModel`
* Add `hidden` property to prevent a layer being rendered
* Update `CanvasController` to render each layer
* Update `AirportModel` to handle the existing format
* Update CYHZ, to have multiple layers, of which Coastlines is hidden by default
