### ISSUE TITLE
Add KEWR (Newark Int'l Airport)

### ISSUE THREAD

**Issue by cheapside2307** [openscope/openscope#1495]
This is to add Newark Liberty International Airport (hopefully in conjunction with KJFK)

**Comment by CanisLupus518** [comment]
@erikquinn I have made some good progress on completing the work started here for KEWR. But I have been unable to figure out the terrain generation. (as a placeholder I copied the geojson file from kjfk).  Is there someone that may be able to help setting up the terrain for KEWR?

**Comment by erikquinn** [comment]
@Fechulo is the qGIS plugin still working, or is it broken? I honestly can't remember...

Also, @CanisLupus518 if you are working on KEWR, please please please open a pull request for it. Even while it is still in-work. Just mark the PR as `WIP`, and feel free to force-push to it or whatever you like. Having the visibility though is critical, for two main reasons-- the first being that if others out there may be working on the same thing, you aren't duplicating effort because you should both be able to see that this issue has a pull request which is being worked on by someone, and the second reason being that if you need help troubleshooting something, we will need the PR anyway. So as soon as you start work on something, we like you to have an issue selected for it (marked as "has pull request"), and a PR open for it, which others can follow as you go along. This strategy has helped us avoid a lot of work being duplicated, or worse-- lost! :)
