### ISSUE TITLE
i can't land the aircraft and i am doing the right commands.

### ISSUE THREAD

**Issue by hadescoder19** [openscope/openscope#1539]
Browser:

Airport:

Approximate play time before issue:

#### Issue Description
_please include any console errors and/or screenshots_ 

#### Steps to reproduce
-

**Comment by Fechulo** [comment]
Hey @hadescoder19! :wave: The more information you give us, the easier and faster we'll be able to help you :slightly_smiling_face: 
What airport are you using?
Does this happen with all aircraft or only some?
Are there any error messages?
What commands are you using?

**Comment by hadescoder19** [comment]
i tried every airport
all aircraft
no error mesages
ILS runway number, then i runway number. when i do the command, the aircraft changes its flight plan and goes out of the radar zone.

**Comment by Fechulo** [comment]
What altitude are the aircraft at when you clear them for the ILS? where are they, relative to the ILS? Any chance you could provide screenshots?

**Comment by hadescoder19** [comment]
3000 or 4000

**Comment by Fechulo** [comment]
Are the aircraft near the ILS and at a heading +/- 30 degrees from the runway? If they are, I'm not sure what the problem is. Any screenshots would help greatly if you could provide some :smiley:

**Comment by VJC009** [comment]
@hadescoder19 make sure your aircraft intercepts the localiser at 30 degrees or less, also ensure they intercept below the glideslope, you can look up IAP charts to find these intercepts. Also when you clear an aircraft for the ILS, the drawn path (pink line) will show a straight line to the intercept point of the localiser, then it bends and follows the localiser till the runway. Also, after you clear the aircraft for the ILS, eg. AAL245 i 23, you can not issue it anymore heading or altitude commands, as those automatically cancel the clearance.

**Comment by poltergeiss** [comment]
> ILS runway number, then i runway number. when i do the command, the aircraft changes its flight plan and goes out of the radar zone.

@hadescoder19 

I was having the same issue at first.  I read through all the commands, scribbled most of them down on a piece of paper for reference with examples, wondered why they'd skirt right past the airport when I cleared them, sifted through the commands again, goofed off with it some more today and figured it out (mainly trial and error and yelling a the dots on the screen).

I wish I poked around here and discovered @VJC009 advice before my trial and error methods.  The charts and airport info for each airport are important because some have certain speed and altitude requirements.  Tried two different airports today.  One I could get the planes to descend to FL 20 and 190 kts. to intercept the ILS, but another airport they had to be at FL 22 and 180 kts.  

Not sure to what extent openScope enforces the airport/airspace restrictions and requirements, besides landings and takeoffs.

Whenever I'm clearing an aircraft, if I plan it right, I can do something like "AA1234 d 22 sp 180 i 23" to get them down to 2,200 ft, 180 kts and intercept the ILS for runway 23 with no problems.
