### ISSUE TITLE
Info about ATCs

### ISSUE THREAD

**Issue by CodeVisio** [openscope/openscope#1556]
Hi,

Sorry to use this issue system for my questions.

I'm interested in ATCs like your openscope.
Where can I get basic and advanced information regarding ATCs in general? How they work, where airports maps can be found, where planes performance data are found etc etc.
I'd like to know more.

Thanks a lot.

**Comment by Hawaiicoder** [comment]
Just google air traffic control.

**Comment by poltergeiss** [comment]
@CodeVisio
> Where can I get basic and advanced information regarding ATCs in general? How they work, where airports maps can be found, where planes performance data are found etc etc.

This covers it all.  Just don't be shocked at the 700+ page PDF, plus any additional PDFs regarding changes.  

https://www.faa.gov/air_traffic/

ATC procedures and phraseology (700+ pages):

https://www.faa.gov/documentlibrary/media/order/atc.pdf

Aircraft information (this is about 700 pages as well):

https://www.faa.gov/documentLibrary/media/Order/Order_7360.1D_Aircraft_Type_Designators_FINAL.pdf

There are a handful of oS videos on YouTube, but If you've never used any ATC software and have no idea how it works (the runways aren't just random numbers, speed is in knots, altitude is referred to as "flight level" and expressed in hundreds of feet - ex: FL 22 is 2,200 ft, FL 100 is 10,000 ft), you definitely need to start with the basics and watch beginner videos with real ATC/TRACON radar screens and controllers.

Airport information is available in oS and they usually provide links towards the bottom with additional info.

Again, best place for airport info:

https://www.faa.gov/air_traffic/flight_info/aeronav/aero_data/Airport_Data/

Here's everything you'd ever want and need to know about JFK.  Even has detailed IAP charts.

https://nfdc.faa.gov/nfdcApps/services/ajv5/airportDisplay.jsp?airportId=Kjfk

Search YouTube for "Kennedy Steve JFK."

**Comment by CodeVisio** [comment]
@poltergeiss 

Thank you a lot. I appreciate that.

**Comment by poltergeiss** [comment]
@CodeVisio

I seriously wouldn't get into the FAA documentation unless you're planning on becoming an airtraffic controller.  Unless you're over the age of 30.  That's the cutoff.

Departures are easy.  Learning how to handle arrivals can be tricky and take time, especially if you have never done anthing like this before.  I really like it.  Just don't take on a busy airport like JFK.  I think Hamburg is one I started with and survived.

If you haven't found these commands yet:

https://github.com/openscope/openscope/blob/develop/documentation/aircraft-commands.md

This guy has 4 oS videos.  Do not bother with the " OPENSCOPE ATC TRAINING" one.  I lasted about 10 seconds because it was nothing but music and that it seemed to be nothing but that and 30 minutes of playing.  I didn't bother to jump ahead to see if he killed the music and just skipped to the other three videos.

https://m.youtube.com/channel/UCwvwgJdigdZAv8-AxQnowJw/search?query=Openscope

VASAviation has some good stuff.  No tutorials,  but still interesting.

https://m.youtube.com/user/victor981994/videos

Unfortunately Kennedy Steve retired, but he is the most entertaining controller I have ever heard:

https://m.youtube.com/playlist?list=PL_ei74pHoe4qfmuVrmQYP1LLJL25paqnr

**Comment by CodeVisio** [comment]
@poltergeiss 

Thanks again.
I don't want to become an air traffic controller for sure :).
I'm very interested however in ATC simulators but I lack a lot of details on this side.

**Comment by poltergeiss** [comment]
@CodeVisio

If, after kicking it around for a bit and still need help, let me know.  Can either hook up on Discord and talk you through some of the stuff and/or send you screenshots of what commands I am typing in to get them where they need to be and lined up so they can and do land.

**Comment by erikquinn** [comment]
Seems to be resolved, so I'll close this issue. Remember, you can always use the openscope slack to message any of us for additional help :)

http://slack.openscope.co/

Closing.
