### ISSUE TITLE
Speed flashes as NaN in aircraft info box when simplified speed option is false

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#165]
#### Steps
- set `Use simplified airspeeds` to `No`
- observer aircraft info box flashes `NaN` intermittently

#### Expected Result
airspeeds are calculated and displayed as a number

#### Result
periodically, airspeeds are calculated as `NaN` in the aircraft infor box

<img width="375" alt="screen shot 2017-01-26 at 6 42 24 pm" src="https://cloud.githubusercontent.com/assets/3325985/22356492/5ea99724-e3f7-11e6-91d0-0f0f47cf2ad2.png">

**Comment by Dabea** [comment]
After looking in to this the speed that was calculated was Signify off and would change biased on how fast or slow the game was running.  Per #271 Will remove the option for the advanced speed calculations. since they where often off by 500+ knots under its better speed calculations.

**Comment by erikquinn** [comment]
@Dabea 
>"use simplified airspeeds - NO"

Note that it was the opposite #271 was requesting. We need to fix and _force_ the "advanced" speed calculations, since they are the realistic ones. You can probably just proceed with repairing it here, and then we can remove the simple speeds in another feature branch, as it is (a) less important, and (b) potentially somewhat spread out.

Definitely with this work here though we will want to at least set the default value of the simplify speeds option to 'no'.

**Comment by erikquinn** [comment]
Rolled into #139.

**Comment by erikquinn** [comment]
Non-simplified speeds are the default behavior now, and the option has been removed.
