### ISSUE TITLE
Log line from previous airport stuck

### ISSUE THREAD

**Issue by OlaRune** [openscope/openscope#1690]
Browser: Chrome 87.0.4280.88

Airport: LOWW Vienna

Approximate play time before issue: Immediate

#### Issue Description
After switching airport from ENGM to LOWW the line "Oslo Approach, IBK222 with you descending through 13000 for 5000" was stuck in the text log above the command input prompt. When there was a message from an aircraft entering the LOWW airspace, both Oslo and Wien was displayed simultaneously, and when there was no message related to LOWW, only the Oslo line was displayed. (see both attached screenshots)

![oslo_wien](https://user-images.githubusercontent.com/25319130/103488606-48092680-4e0e-11eb-8a48-187351a4d7c4.png)
![only_oslo](https://user-images.githubusercontent.com/25319130/103488605-47709000-4e0e-11eb-8be3-4664987fcb5a.png)

#### Steps to reproduce
This error is easy to reproduce:
1. Start a game at an arbitrary airport.
2. Open the airport selection menu.
3. Wait for an aircraft to approach.
4. Just as the aircraft reports that it is with you, switch to another airport.
5. The line from the first airport is now stuck when playing at the new airport.

**Comment by cake-pie** [comment]
The display behavior of log lines is governed by:
https://github.com/openscope/openscope/blob/67f23ecfa27e73eb698ee7fe7c008ac03fdb8d3e/src/assets/scripts/client/ui/UiController.js#L638-L644

`GameController.game_timeout()` is used to set a 3 second timer, added to the array `game.timeouts`
- after 3 seconds elapse, the log line will be given `hidden` class which is `opacity: 0;`
  - due to `transition: opacity 10s ease;` the line fades out over 10 seconds
  - a standard javascript `setTimeout` is started for a further 10000 milliseconds (10s)
    - this removes the log line from the DOM after the fade out is complete

When airport is changed, it fires `EVENT.AIRPORT_CHANGE` on the event bus. `AppController.onAirportChange()` is one of the event handlers that responds to that, and among other things it will [call `GameController.destroyTimers()`](https://github.com/openscope/openscope/blob/67f23ecfa27e73eb698ee7fe7c008ac03fdb8d3e/src/assets/scripts/client/AppController.js#L297) thereby discarding all outstanding timers in `game.timeouts`.

Thus, if a log line is less than 3 seconds old when airport is changed, the timer that will start its fadeout gets discarded and the line is stuck forever.  A log line that is 3 to 13 seconds old i.e. has started fading out, will correctly continue to fade out and get removed from the DOM.

**Comment by cake-pie** [comment]
Solution: wipe the log clear upon airport change
```
    /**
     * @for UiController
     * @method onAirportChange
     */
    onAirportChange() {
        this.$log.empty();
    }
```

Due to dependency on ed96527104e3890ab5ae2f360f9921993f423d13 , either I can solve this in the same PR as #1740, or if that is objectionable then this gets blocked until that PR is merged first.

**Comment by OlaRune** [comment]
I'd say just solve it in the same PR, but I'm kind of an anarchist when it comes to development processes. Some people whine at work but at least I fix stuff so they only whine a little...

**Comment by n8rzz** [comment]
I'd refer this as it's own PR simply because we use issue links and auto issue moves with our PRs.  It'll happen automatically and atomically.  If that weren't the case, I'd say toss it in #1740.

**Comment by cake-pie** [comment]
Fix is basically https://github.com/cake-pie/openscope/commit/dce18519ddc14fde15259d3d463607e1e737b12b but as discussed will wait on #1740 since some kind of rebase/merge conflict is likely to occur
