### ISSUE TITLE
Runtime error when defining spawnPattern with both origin and destination (and origin is implemented)

### ISSUE THREAD

**Issue by OlaRune** [openscope/openscope#1762]
Browser: Mozilla Firefox 85.0.1
Airport: ESSA (while implementing, though it doesn't really matter)
Approximate play time before issue: At startup

#### Issue Description
_Note: I know that this use of spawnPatterns isn't recommended (and apparently not supported...) because of other issues, such as no handling of separation at spawn when aircraft from different spawnPatterns spawn along the same airway. Though my guess is that the plan is for it to be supported in the future, which is why I'm reporting this as an issue._

When adding spawnPatterns for arrivals (though I would guess the corresponding problem happens for departures) where both `origin` and `destination` are entered, and the `origin` is an airport that is implemented in the sim, a runtime error is thrown. Everything works fine when the `origin` airport is not implemented.

Works fine (Heathrow is not in sim):
`{
            "origin": "EGLL",
            "destination": "ESSA",
            "category": "arrival",
            "route": "INVOL.N866.BEDLA..ELTOK.ELTOK7M.ESSA01R",
            "altitude": "18000",
            "speed": "330",
            "method": "random",
            "rate": 0.7,
            "airlines": [
                ["sas/short", 1],
                ["baw/short", 1]
            ]
        }`

Not working (Manchester is in sim):
`{
            "origin": "EGCC",
            "destination": "ESSA",
            "category": "arrival",
            "route": "INVOL.N866.BEDLA..ELTOK.ELTOK7M.ESSA01R",
            "altitude": "18000",
            "speed": "330",
            "method": "random",
            "rate": 0.7,
            "airlines": [
                ["sas/short", 1],
                ["baw/short", 1]
            ]
        }`

The error is `Uncaught TypeError: Expected instance of RunwayModel, but received null` and below that `setDepartureRunway Fms.js:1020`. I assume that it is expecting me to include the complete route from departure runway -> SID -> route -> STAR -> arrival runway, but this shouldn't be necessary.

#### Steps to reproduce
- Add a spawnPattern where the origin is included in the sim (see example above)
- Build and start
- Problem occurs right after loading

**Comment by cake-pie** [comment]
Haven't delved into the code to trace how exactly that error occurred, but I'm fairly certain `origin` is for departures only, and `destination` is for arrivals only. You should leave an empty string where not relevant.

In the ESSA PR you have [two arrival spawn patterns](https://github.com/openscope/openscope/blob/3eeca88afc842d1532a39f8b6d015458df9e2d9c/assets/airports/essa.json#L3273-L3300) with identical routes, differing only in their airport of origin.

I'm not sure it's necessary (or intended, or even desirable) to have multiple spawn patterns with completely identical routes. Arrivals are spawned at or approaching STAR entry points; the rest of their flight plan prior to that does not matter. Multiple flights coming "via the same route" can be consolidated into a single spawn pattern with appropriate weighting; in the ESSA example you could just use a single entry with `"rate": 1.1` and airline weights adjusted accordingly (i.e. sas 7, baw 7, ezy 2, nax 6).

Each individual spawn patterns incurs some overhead -- a separate timer gets created for each one; each timer is checked every sim update tick. If your intention is to model every possible origin airport with its own separate spawn pattern, that can start to add up.

If you absolutely insist on keeping separate entries (still not recommended -- read on below), try leaving the origin blank and use `_comment` to make a note of the origin airport instead.

*Independent of the above,* you've also already noted the problem of arrivals colliding or coming into conflict with each other because separation is not ensured between aircraft from different spawn patterns that share parts of their route. The #1367 hotfix dealt with the issue by simply removing all such conflicting spawn patterns (e.g. KBOS had spawn patterns [for both `AJJAY.OOSHN5.KBOS22L` and `FERNZ.OOSHN5.KBOS27`](https://github.com/openscope/openscope/blob/53e1722/assets/airports/kbos.json#L996-L1047) but the latter was removed and only the former remains.)

I do hope to come up with [a better solution](https://github.com/openscope/openscope/issues/1746#issuecomment-771354729) but that is very much theoretical at the moment. Until something along those lines has actually been implemented, you will resurface the conflicting arrivals issue by making spawn patterns with common route -- so please don't!

**Comment by erikquinn** [comment]
>I'm not sure it's necessary (or intended, or even desirable) to have multiple spawn patterns with completely identical routes.

In fact, this is directly prohibited because there is no logic protecting these patterns from spawning conflicting aircraft. Given enough time, because the aircraft spawn timing is random, you will eventually have two aircraft entering the airspace who have already lost separation. For this reason, _even all streams which merge outside the approach control_ should only have ONE spawn pattern implemented. Currently, that's the only way to ensure the user is not fed a deal.

**Comment by OlaRune** [comment]
@cake-pie @erikquinn I understand that it is not viable to use a separate spawnPattern for each airport that has traffic to/from ESSA. I was experimenting a bit and have since then decided to do it the old-fashioned way, so don't worry about that.

However, I assume that both origin and destination is something that is supposed to be supported later, when/if separation between independent spawnPatterns is implemented. At least for me it feels like aircraft having another airport as destination/origin adds a bit of immersion, but it is not super important.

I opened this issue because I still believe it is a bug, albeit one that only has impact on future functionality. @erikquinn Feel free to close the issue if you think it is irrelevant, or it could be kept open as a reminder that this will have to be fixed when/if the mentioned functionality is introduced.

**Comment by cake-pie** [comment]
No idea about whether there are plans to support having both origin and destination.

Regardless of that, I think this issue is still interesting for defensive coding reasons:
- there is no protection against an `arrival` spawnPattern having `origin`, or coversely, `departure` with `destination`
- the `origin` should have no impact on `arrival` spawnPattern, yet somehow behavior differs depending on its value, this betrays some error in logic somewhere that is worth rooting out and fixing.

**Comment by OlaRune** [comment]
> * there is no protection against an `arrival` spawnPattern having `origin`, or coversely, `departure` with `destination`

I don't think we would want this protection. If you supply both at the same time they show up correctly as origin and destination on the flight strip.

> * the `origin` should have no impact on `arrival` spawnPattern, yet somehow behavior differs depending on its value, this betrays some error in logic somewhere that is worth rooting out and fixing.

I agree, this is what I believe needs to be fixed. In my humble opinion the origin should show up on the flight strip but not have any impact on the functionality other than that.

I can see cases where this functionality can be put to use today (before introduction of the separation guarantee discussed earlier). Say I implemented a small airport that only has connections to a few other airports and these can be safely added as separate spawnPatterns with arrivals from different directions. Then it would be nice to have arrival flight strips with the origin airport.

**Comment by OlaRune** [comment]
@cake-pie @erikquinn 

There is a simpler and more futureproof solution (I think) to allowing aircraft having both origin and destination.

To avoid the issue above the spawnPattern syntax could be changed a bit.

1. Remove origin and destination from the (outer) spawnPattern definition. It is deriveable from which airport file we are in and whether it is an arrival or departure annyway.
2. Add origin and destination as options to each airline in the spawnPattern instead. These are only used to populate the flight strip.

Example for combining the two patterns in the original issue text.
`{ "category": "arrival", "route": "INVOL.N866.BEDLA..ELTOK.ELTOK7M.ESSA01R", "altitude": "18000", "speed": "330", "method": "random", "rate": 0.7, "airlines": [ ["sas/short", 1], ["baw/short", 1] ] }`

TBC I will edit this on my computer. This coding was a pain in the ass on mobile...

**Comment by erikquinn** [comment]
Honestly, that seems pretty complicated; I'm not sure I follow it completely. Separately though--

> 1. Remove origin and destination from the (outer) spawnPattern definition. It is deriveable from which airport file we are in and whether it is an arrival or departure anyway.

We are trying to make small steps toward supporting multiple airports, so it was intentional to keep origin/destination information _separate_ from the "airport". When multiple airports are usable (say KIAD/KDCA/KBWI), the spawn patterns should not be included with the airport file, but rather in a central place, likely the facility file, in accordance with #47. That was the reason for the verbosity, even though one could infer that it was an arrival/departure to "the airport" based simply on its category; it just wouldn't have the flexibility of allowing multiple airports to be "the" airport.

There could well be a better solution than what was implemented, but it should be shaped taking those future plans adequately into consideration.

**Comment by OlaRune** [comment]
> Honestly, that seems pretty complicated; I'm not sure I follow it completely. Separately though--
> 
> > 1. Remove origin and destination from the (outer) spawnPattern definition. It is deriveable from which airport file we are in and whether it is an arrival or departure anyway.
> 
> We are trying to make small steps toward supporting multiple airports, so it was intentional to keep origin/destination information _separate_ from the "airport". When multiple airports are usable (say KIAD/KDCA/KBWI), the spawn patterns should not be included with the airport file, but rather in a central place, likely the facility file, in accordance with #47. That was the reason for the verbosity, even though one could infer that it was an arrival/departure to "the airport" based simply on its category; it just wouldn't have the flexibility of allowing multiple airports to be "the" airport.
> 
> There could well be a better solution than what was implemented, but it should be shaped taking those future plans adequately into consideration.

I realize that my description wasn't very clear as to what I'm suggesting and what I want to solve, so I'll give it one more shot and see what you think about it.

_Note: I'll just describe this for arrivals but the same argument is valid for departures as well, and should be solved in the same way._

**What I want to solve**
Right now arrivals from many different airports are combined into fewer spawnPatterns (and most likely in the future as well, even when separation is guaranteed between different spawnPatterns). This makes it impossible to include information about each arrival aircraft's `origin` airport in the flight strip, since one spawnPattern can only have one `origin` and one `destination`. I think that this information would add bit of immersion for the user, and is therefore worth including.

**Suggestion in broad terms**
Move the `origin` and `destination` information from being common for the whole spawnPattern to instead be included for each `airline` in the spawnPattern. This allows arrivals spawned from the same spawnPattern to have different origins.

**Details**
For each `airline` in an arrival spawnPattern, include the `origin` and `destination` as two strings after the weight, for example:
`["sas/short", 1, "EGLL", "ESSA"]`
The first string is the `origin` and the second string is the `destination`. For arrivals we allow the airport developer to leave the first one empty if he doesn't want to include the `origin` on the flight strip (and conversely the second one empty for departures).

**Regarding your concern for supporting multiple airports within the same airspace in the future**
My suggestion of inferring the destination airport from the airport file can be completely disregarded, that was not a good suggestion. Instead this information can be taken from one of two places.

1. From the `destination` defined for each airline.
2. From the runway at the end of the `route` in the spawnPattern.

**Regarding what I said about different airports having different spawnPatterns**
Since aircraft arriving to different airports within the airspace would need a different `route`, because they have different STARs and different target runways, they would have to be handled in different spawnPatterns anyway.

**Resulting changes to all airport files**
The changes to airport files would be rather small to just get things working the way they worked before. For arrivals we leave the `origin` string empty for each airline, and for departures we leave the `destination` string empty. Then if airport developers want to start including the information that can be done later, and if nobody wants to put in the work, things would work just as before for that airport.

Is that a bit more understandable than before? Do you still think this seems complicated? I personally don't think it would be very complicated.

**Comment by erikquinn** [comment]
I guess more than "complicated" what I meant to say was that it seemed like excessive granularity and verbosity, since you would have to specify for every single airline entry. Usually I would think that would be more of a hassle than a benefit, but in many cases I can see how the it would be worth the additional work, especially considering that a lot of the spawn patterns are derived from real-world traffic data from flightradar24 anway. And if you _didn't_ care to specify different origins, you could always do a multiline-select and just type in the same city pairs for all and be done in like 10 seconds. So I guess after I think about it, it's definitely valuable, and without any real downsides (other than being another "breaking" change that would require updating _every_ airport file again, which is a doozy 😉).

One thing to keep an eye on though, is that it may be that the `origin`/`destination` keys are being used to indicate whether an aircraft is landing or not... for example, I think the overflights have neither defined, to indicate they won't land, though they use a different category... I guess my point is that it may not be _only_ looking at the category to determine how to treat the aircraft being spawned. Or maybe it's fine, I don't quite remember.

> Right now arrivals from many different airports are combined into fewer spawnPatterns (and most likely in the future as well, even when separation is guaranteed between different spawnPatterns). This makes it impossible to include information about each arrival aircraft's origin airport in the flight strip, since one spawnPattern can only have one origin and one destination.

Exactly. The tentative plan for next steps at the time was to change the origin/destination values to a weighted array, like those used in airlines: `origin: [['KDCA', 2], ['KBWI', 1], ['KIAD', 5], ['KACY', 1], ['KJFK', 3], ['KEWR', 5], ['KLGA', 2], ['KBOS', 3]],`. You'd be achieving the same thing in a different way, which would at the same time facilitate an even deeper level of specificity with about the same amount of work.

> Regarding your concern for supporting multiple airports within the same airspace in the future
>My suggestion of inferring the destination airport from the airport file can be completely disregarded, that was not a good suggestion. Instead this information can be taken from one of two places.
>
>1. From the destination defined for each airline.
>2. From the runway at the end of the route in the spawnPattern.

I like the former more than the latter, as it's more cut and dry. There might be times where the routing they would put in would not include the airport anyway (even if we said "please do as part of the spec"). The airport is only really at the end of the route (like you said) to allow us to specify a runway, because many arrivals will have different chains of fixes that will apply based on which runway you are assigned. Whereas using the airline entry to show they are arriving at the airport would be a very clear indicator by comparison.

> Since aircraft arriving to different airports within the airspace would need a different route, because they have different STARs and different target runways, they would have to be handled in different spawnPatterns anyway.

In many cases, they actually would _not_ need a different route. For example, KIAD/KHEF use the same route, while other dulles satellite airports (shenandoah area of PCT) use the same routing to HWY/FRR/OKV/FDK/HGR/MRB/etc. So there is definitely value in sharing a route among multiple destinations, which would be possible under your proposal of specifying orig/dest by airlines. Real world, they are often treated as the same airport, ie a restriction of `IAD 15 MIT` would actually apply for a IAD following a HEF following a IAD, etc.

> The changes to airport files would be rather small to just get things working the way they worked before. For arrivals we leave the origin string empty for each airline, and for departures we leave the destination string empty. Then if airport developers want to start including the information that can be done later, and if nobody wants to put in the work, things would work just as before for that airport.

Yep, exactly, that sounds good.

It's all more clear now, and after thinking it through in the past few days, I'm liking it more and more. Thanks for the detailed followup to clear things up! 👍

**Comment by OlaRune** [comment]
Thanks @erikquinn for your verbose reply. I agree with almost everything you said and I will create a separate issue for this (which means we may close this issue?).

Just one thing, weighting the origins/destinations does not give exactly the same functionality, because it means we can't control which airlines/fleets arrive to/from which airports. In that regard my solution is better.

**Comment by erikquinn** [comment]
> Just one thing, weighting the origins/destinations does not give exactly the same functionality, because it means we can't control which airlines/fleets arrive to/from which airports. In that regard my solution is better.

Exactly, I agree on your solution. When I said `You'd be achieving the same thing in a different way, which would at the same time facilitate an even deeper level of specificity with about the same amount of work`, I meant _you_ and _your_ solution would do the same that mine did plus more. So I'm on board!

Yes, we can make a fresh issue to cover the described work, just throw in a `Related: #1762` so we can backreference this conversation if we ever come back to the PR after it all is completed and merged to get the full backstory.

Closing!

**Comment by cake-pie** [comment]
Since the "show both origin and destination" immersion feature request is going to be rolled into the airport/facility/sector refactoring as a separate issue for future work, I don't suppose ya'll will mind me using this issue number for tackling the problem as it exists in the current implementation.

> no protection against an `arrival` spawnPattern having `origin`, or coversely, `departure` with `destination`

`spawnPatternModelJsonValidator` isn't adequate.

I'd already been planning to do some work on json schemas and json validation anyway, so this part of the issue will naturally be addressed as part of that work.

> the `origin` should have no impact on `arrival` spawnPattern, yet somehow behavior differs depending on its value, this betrays some error in logic somewhere that is worth rooting out and fixing.

Since validation didn't catch the currently invalid combination of both origin + destination being present, those values are ingested into the `SpawnPatternModel` and passed wholesale by `SpawnScheduler` to `AircraftController` for aircraft spawning, creating an `AircraftModel` with corresponding `Fms`. `Fms` takes that data and initializes arrival/departure airport+runway as long as destination/origin respectively are non-empty strings:

`Fms.init()`:
https://github.com/openscope/openscope/blob/07f1fc504ab42f72448c8b82ed7547a6acc0e433/src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js#L274-L277

https://github.com/openscope/openscope/blob/07f1fc504ab42f72448c8b82ed7547a6acc0e433/src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js#L311-L314

https://github.com/openscope/openscope/blob/07f1fc504ab42f72448c8b82ed7547a6acc0e433/src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js#L352-L355

**Comment by cake-pie** [comment]
> When adding spawnPatterns for arrivals (though I would guess the corresponding problem happens for departures) where both `origin` and `destination` are entered, and the `origin` is an airport that is implemented in the sim, a runtime error is thrown. Everything works fine when the `origin` airport is not implemented.

To be precise, an error will be thrown if the airport
- is implemented in the sim
- was not played yet within the same session

No problem occurs if the airport is not implemented in the sim (e.g. EGLL) because the [attempt to fetch the corresponding AirportModel](https://github.com/openscope/openscope/blob/c391f605530dac4c5e9f8554d4ecf56c5b17f28d/src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js#L357) in `_initializeDepartureAirport` fails and thus [prevents progressing further](https://github.com/openscope/openscope/blob/c391f605530dac4c5e9f8554d4ecf56c5b17f28d/src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js#L368-L370) in `_initializeDepartureRunway`.

With an implemented airport (e.g. EGCC) the corresponding AirportModel will be fetched. However, the AirportModel for every airport in the load list is [initialized with only barebones data at app start](https://github.com/openscope/openscope/blob/c391f605530dac4c5e9f8554d4ecf56c5b17f28d/src/assets/scripts/client/airport/AirportModel.js#L344-L353) and will only be fully fleshed out from its airport json if and when loading it up to be played (either as initial airport, or the user switches to it). Thus, when `_initializeDepartureAirport` tries to get a RunwayModel from the skeletal AirportModel, it obtains a null value, and error occurs when that null gets passed along when it calls `setDepartureRunway`.

This uncovers another problem in the initialization of `Fms` in that these four:
https://github.com/openscope/openscope/blob/c391f605530dac4c5e9f8554d4ecf56c5b17f28d/src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js#L274-L277
not only should be gated behind whether aircraft is arriving/departing, but strictly speaking they *expect to be called only in relation to the current airport* and passing any other value as the argument should be invalid.
