### ISSUE TITLE
Departures leave and reenter from center control at airports with complex airspace

### ISSUE THREAD

**Issue by Aviation34L** [openscope/openscope#1844]
Airports with complex airspace (sectors with different ceiling altitudes) can cause departures to leave a sector of the airspace as they climb, then reenter in another sector with a higher altitude ceiling. For example, at KPHL, I've had aircraft on the PHL2 PTW departure climb heading southeast, then I assign them to head north and they leave the airspace (sector 3) as they climb above 10,000 feet, because they are assigned to climb via SID to 12,000. They then reenter the airspace (sector 1) as the ceiling for that sector is 13,000 feet. When this happens, the sim reads back "Philadelphia Tower, [callsign], ready to taxi"

**Comment by erikquinn** [comment]
Hi @Aviation34L!

The "ready to taxi" call is very odd and definitely not correct. But other than that, everything is behaving as expected. I will create a separate issue for fixing the taxiing call.

So the short version of the issues at play here is that the airspace you own is the _only airspace you can use_. This means you will have to change your controlling behaviors to keep your aircraft within your airspace.

To your example of a PTW departure, they must only be assigned as high as 10,000 while in area 3. Once they pass into area 0, you can assign 12,000, and when entering area 1, up to 13,000. So the action of giving them direct PTW and climb to 12,000 while in area 0 is what is not correct. You will need to give them multiple climb instructions to step them up to 13,000. (Fun fact: the reason PHL has a lower ceiling in areas 3, 5, and 8 is because EWR arrivals from the southwest are descending via the PHLBO3 arrival, directly above PHL airspace).

![image](https://user-images.githubusercontent.com/5103735/140408146-ee426f94-9e08-4479-9454-d983361ff3e7.png)

Also keep in mind that you _cannot issue a "climb-via" instruction on the PHL2 departure_. It does not have any posted altitude restrictions, so a climb-via is not possible. They are simply instructed by clearance delivery to climb to 5,000ft, and they will be issued step climbs by departure. A climb-via SID will have published crossing restrictions, like the CHUWY1 out of KDEN, for example.

![image](https://user-images.githubusercontent.com/5103735/140407933-253888c6-5998-4321-b4a9-ac18d2f69a6f.png)

**Comment by erikquinn** [comment]
If you have further questions, feel free to continue the conversation in here! We will still see the notifications. But I will be closing this issue as the "taxi" issue has been recorded in #1852, and there are no other issues with the sim which require fixing.

Closing!
