### ISSUE TITLE
Support runway/fix specific tower assigned headings

### ISSUE THREAD

**Issue by CanisLupus518** [openscope/openscope#1854]
There are some airports, like KPHL and the PHL2 SID, that assign departure headings to aircraft based on the exit fix they have filed as well as the runway they are using. Currently this has been baked into the SID but only works for the default runway configuration in the airport file and would not behave well if the runway config is changed with #34 

I propose a new tower section in the airport cfg where departure headings can be specified unique to runway and/or SID. This would also enable support for smaller airports that don’t have SIDS to be able to define tower assigned headings.

**Comment by erikquinn** [comment]
Perhaps an easy way to fix this and other issues is to specify some commands in each spawn pattern which are run when the aircraft is spawned... Consideration for the departure runway would still need to be specified for the desired result of course...

Keep in mind that the heading would depend on BOTH the runway and routing. Listing instructions for each spawn pattern off each runway should be the way to handle it all I think, and will also fix some other weaknesses (like arrivals with weird descent profiles on spawn can be given crossing restrictions that aren't charted on a STAR). 

Unfortunately very verbose, but the specificity is needed, because it would be much harder to specify from the airport level what to do with every conceivable route that the spawn patterns could use, rather than the other way around like this.

Maybe something like this?

Departure Spawn Pattern:
```javascript
commands: {
    departureRunway: {
        8L': ["fh 070"],
        '8R': ["fh 070"]
        '9': ["fh 090"],
        '26L': ["fh 290"],
        ...
    }
}
```

**Comment by CanisLupus518** [comment]
I like this approach. Let’s see what I can do.

**Comment by CanisLupus518** [comment]
@erikquinn thinking forward to when we might want to be supporting multiple airports in a single file, I was thinking about the fact that STARS are not necessarily tied to a single airport. They can have transitions to runways at nearby airports as well. Because of this I assume STARS will be attributed to the sector eventually rather than the airport, and will need to be able to reference runways at multiple airports. I was thinking similar naming convention as the SIDS use like perhaps: 
`commands: {
    arrivalRunway: {
        'KPHL8L': ['cr btoga a130 s280'],
        'KPHL8R': ['cr btoga a130 s280'],
        'KPHL9': ['cr btoga a130 s280'],
        'KPHL12': ['cr btoga a130 s280'],
        'KTTN26L': ['cr btoga a110 s250'],
        ...
    }
}`

thoughts?

**Comment by n8rzz** [comment]
hmm, not directly related to this, but the concept of a `sector` is interesting.  its something we've struggled with; how can we tie multiple airports together to someday have proper handoffs and maybe even multiplayer?  A `sector` concept  may be a step in that direction.

**Comment by CanisLupus518** [comment]
> hmm, not directly related to this, but the concept of a `sector` is interesting. its something we've struggled with; how can we tie multiple airports together to someday have proper handoffs and maybe even multiplayer? A `sector` concept may be a step in that direction.

@n8rzz #47 would be a great place to have this discussion.  I have been trying to identify small-ish things that can be addressed that would help pave the way towards that end goal.  This current issue is one of them.

**Comment by CanisLupus518** [comment]
After thinking more about my comment about runway names, I think I confused myself. The spawn pattern will have only one destination, so having that destination as part of the runway name does seem redundant. Using only the numbers is probably fine.

**Comment by erikquinn** [comment]
For what it's worth, yes, we would at some point want to move the stars out of the airport, but the sector would still be too specific. i.e. if we had 10 sectors, you'd define the same stars ten times. It should go in a higher level, most likely at the `Facility` level (see #47).
