### ISSUE TITLE
Slow performance with lots of aircraft

### ISSUE THREAD

**Issue by ron-eo** [openscope/openscope#232]
Hi folks!

I'm running on Windows 8.1 and Firefox as the browser (45.7.0) and, once the number of aircraft on the strip starts to get larger, the whole simulator slows right down. You can actually see this in the time at the top left...the seconds take progressively longer to tick by.

Is there something I can set in Firefox (or any browser) that could fix this issue, or is it just me?

**Comment by n8rzz** [comment]
TL;DR yes, its an issue.  yes, we're working on it. yes, there are a few things you can do.

- Set the Draw Selected Paths option to Selected or Never
- Turn off any terrain (which might not be possible at the moment because #203 is part of the next release and that has not been released yet)
- Turn off SID Display (the airplane icon)

Other than that, there isn't much for you, as a user, you can do. 

For us, as the developers, there is a lot of work happening that is directed directly at this problem.  But you likely won't see any noticeable progress for another few months.

**Comment by erikquinn** [comment]
In the meantime, I can at least say that if you use Chrome, in my experience, you will see at least 2-3 times better performance than with Firefox. (IE is even worse though)

**Comment by ron-eo** [comment]
Thank you, folks! I appreciate the info and I did look at all the issues before I posted this one. I'll see if I can get Chrome on my machine. Cheers !

**Comment by scott-j-smith** [comment]
I use Chrome and I still see issues at airports with heavy traffic.   But I rarely crashes, and I just increase the timewarp to 3 or 4 to make up the difference.   The only airport I see regular game crashes in is WMKK (Kuala Lumpur), which might be an airport issue, not a simulation issue.

**Comment by ron-eo** [comment]
Thanx, scott-j-smith! Yes, I tried the time warp at x2 and it was ok for a while so I tried the x5 and it was very jumpy. I'll have to try the x3 and x4.
