### ISSUE TITLE
canvas refactor

### ISSUE THREAD

**Issue by n8rzz** [openscope/openscope#236]
- general canvas refactorings
- fix padding on scale indicator

**Comment by tedrek** [comment]
I'm not an experienced Javascript/HTML5 canvas optimizer so bear that in mind.  I did a couple of branches testing performance, trying to make it multi canvas where the background didn't have to be redrawn every frame.  I couldn't get any significant performance benefits, and performance was significantly worse on my hardware without good 2d/3d accelerated hardware.  This was probably 2014/2015.  I tried both an approach where the canvases were layered and let the browser do the compositing, and a blit type approach where image data was copied from one canvas to another rather than using the drawing primitives.  I also tried an approach where the data blocks were persistent HTML elements, again the performance was worse than what is done currently.  It appeared that compositing the multiple items was really costly compared to just drawing them completely from scratch.  So my strong suggestion would be to do some cheap benchmarking before going to far on actual refactoring for multiple canvases.

**Comment by n8rzz** [comment]
@tedrek are measuring performance of the initial draw?  Or the performance of re-drawing of each subsequent frame _after_ the initial draw?

I would expect the initial draw to be about the same performance as we see now.  However, I would expect the following renders (where we re-draw only the moving elements) to be significantly more performant.

>I'm not an experienced Javascript/HTML5 canvas optimizer so bear that in mind

^^ that part may be biting you a little bit here in that your 'terrain canvas' may actually be re-drawing each frame.

**Comment by tedrek** [comment]
I was measuring sustained frame rate during play as the metric.

I too expected it to be better performing, and I think it may have been in terms of game code time.  However the cost of the browser compositing multiple layered canvases together via transparency was enough higher to outweigh the drawing time saved on my lower end hardware and break even if that on my higher end hardware.  Similiarly the approach I used to copy the already drawn elements from one canvas to another ended up costing more time copying data around than just drawing the elements from scratch in the one canvas.  I was surprised (and disappointed).

The background canvases were definitely not being modified every frame by the game code, only the aircraft/datablock canvas was being redrawn.  The basic algorithm was:
* Load airport
* Create background canvas
* Draw fixes, terrain, etc. on background canvas
* Create aircraft canvas
* Enter main loop
*  -> Clear and redraw aircraft canvas

Given the results I saw, I had no reason to believe the background canvas was doing an automatic redraw on it's own and I am certain the game code was not redrawing it.  I'm more thinking there may have been some hidden trick to layering or blitting which would hit a faster path than the ones I could find.  I am letting you know somebody has tried to get the low hanging fruit here and there wasn't any in two or three approaches, if anybody wants to try this path again it's probably a good idea to benchmark early in the process to validate the approach before getting too deep into refactoring as there appears to be some hidden costs, especially on lower end hardware which currently run the game well enough.
