### ISSUE TITLE
AeroMexico Connect (SLI)

### ISSUE THREAD

**Issue by headphase** [openscope/openscope#309]
Aeromexico's regional subsidiary (IATA: **SLI**, callsign **COSTERA**) is currently mashed in with the mainline .JSON as "amx/short" but I think the airline needs its own file as it operates with different types (E145/E170/E190) under a different certificate and callsign.

https://en.wikipedia.org/wiki/Aerom%C3%A9xico_Connect

I'm not sure what the least labor-intensive way is to go about finding which airports currently use "amx/short" in their Spawnpatterns; would it break the game if we were to make this change without digging through each affected airport?

**Comment by indianbhaji** [comment]
Yes, you do need to update every single airport that has reference to amx/long or short. It may be worth checking if the callsign is actually used through LiveATC or something though, since sometimes subsidaries use the callsigns of their parent company. An example of this is KLC, KLM Cityhopper which has the callsign 'CITY' but uses the callsign 'KLM'.

**Comment by indianbhaji** [comment]
The best way to update each entry is just going through every file! I had to do this when fastGA existed and we had to merge it into the 'n' airline

**Comment by erikquinn** [comment]
It's easy enough to update the airport files with the new airline. Just find and replace `amx/short` with `sli`, and check the results.

**Comment by headphase** [comment]
I'm using atom to edit; I wonder if it's able to run find/replace on an entire folder... I'll have to poke around.

**Comment by n8rzz** [comment]
`ctrl + shift + f`

**Comment by headphase** [comment]
Turns out it was only on JFK; I will roll this into the PR for #242 when that's finished :)
