### ISSUE TITLE
Incorrect runway alternative chosen for SIDs

### ISSUE THREAD

**Issue by ij1** [openscope/openscope#383]
It seems that the second aircrafts picks incorrect runway from the SID "rwy" alternatives.

E.g.:

1. Choose LOWW
2. Select an aircraft bound to OSPEN
3. Issue "taxi 11 caf cvs" and then "to" to it
4. Repeat for another aircraft bound to OSPEN but use runway 16 instead of 11
5. The second aircraft seems to head towards WW100 rather than WW269

**Comment by panther2** [comment]
I have tested and got it hte other way round:

![open](https://cloud.githubusercontent.com/assets/20812775/25503835/f9f66a2c-2b9b-11e7-9b5e-59331295e8c9.PNG)

VLG started from Rwy 16, EWG from Rwy11 - and both headed to WW269...

**Comment by ij1** [comment]
Right, I also got it that way a few times (but it isn't correct either).

**Comment by panther2** [comment]
Yes, I did not intend to contradict but to confirm the issue. :smile:

**Comment by indianbhaji** [comment]
It's probably because the aircraft is _expecting_ runway 11 and therefore selects the `OSPEN1A1 departure which is only for runway 11. @erikquinn @n8rzz could maybe confirm this?

**Comment by n8rzz** [comment]
I'll take a look at this sometime today.  We should be able to figure this out whats going on by stepping through [AircraftCommander.runClearedAsFiled](https://github.com/openscope/openscope/blob/develop/src/assets/scripts/client/aircraft/AircraftCommander.js#L244).

**Comment by erikquinn** [comment]
@indianbhaji may be on the right track. It won't "select the `OSPEN1A` departure which is only for runway 11", but it will choose a runway it thinks it will get before it's told anything. And it's possible that runway is not overwritten properly when he taxies to a runway that isn't the one he initially had, and that's why his fms takes him on the portion of the sid for the runway he didn't actually end up using after all...
