### ISSUE TITLE
Invalid coordinates in Lulea Airport

### ISSUE THREAD

**Issue by RNGFavorsNoobs** [openscope/openscope#456]

**Comment by ij1** [comment]
I tried to look for an invalid coordinate but I think there weren't any.

Nevertheless, loading Luleå was often not successful but I guess the issue is not in coordinates but in the spawn patterns. The error seems racy though as Luleå occassionally loads fine (and IIRC I didn't see the failure with develop branch so something unrelated to the airport json itself is perhaps fixed there).

**Comment by n8rzz** [comment]
looks like the procedures on this airport only have the `rwy` segment defined.  that is where the problem is for sure.

**Comment by ij1** [comment]
There's now #494 that should take care of Luleå Airport.
