### ISSUE TITLE
EGNM contains departure spawnPattern not associated with default runway

### ISSUE THREAD

**Issue by Jelmerkeij** [openscope/openscope#492]
Couldn't find this in the open issues list, sorry if I might have overlooked it. This occurs when playing EGNM.
When there are no aircraft in the airspace but 1 arrival is about to enter the game crashes after repeatingly throwing this error:

```
Uncaught TypeError: Cannot read property 'isHold' of undefined
    at AircraftInstanceModel._shouldEnterHoldingPattern (AircraftInstanceModel.js:1877)
    at AircraftInstanceModel.updateFlightPhase (AircraftInstanceModel.js:940)
    at AircraftInstanceModel.update (AircraftInstanceModel.js:1903)
    at AircraftController.aircraft_update (AircraftController.js:240)
    at App.update (App.js:409)
    at App.js:406
```

**Comment by n8rzz** [comment]
@Jelmerkeij thanks for the bug report!  

We are in the midst of a major airport refresh.  A lot has changed in the last six months with how airport files are handled and many of them need updating.  This airport included.

This particular bug is related to #53 and is occurring because of an incorrect spawnPattern (the thing that defines basic aircraft properties as they get created in the sim).  This particular spawnPattern is a departure for the `EGNM.NELSA.NELSA` route.  `ENGM` defaults to runway `14` and this pattern only works for rwy `32`.  So when this aircraft attempts to spawn, it cannot create a route in the fms because the active runway does not match the runway defined in the SID.  This leads to an `undefined` `currentWaypoint` and the first block that gets hit that needs the `currentWaypoint ` is the block that is causing your error: `Uncaught TypeError: Cannot read property 'isHold' of undefined`

This airport is going to need updates in addition to the one required to fix this issue.  Unfortunately, I cannot give you a timeframe for these changes other than to say _soon_.  We are working through all the airports and this one is on the list.

**Comment by indianbhaji** [comment]
@n8rzz ENGM is in Oslo and EGNM is in the UK

**Comment by n8rzz** [comment]
ha, sorry.  I meant `EGNM`

**Comment by n8rzz** [comment]
@Jelmerkeij it seems my esteemed colleague is feeling industrious today and ahas already knocked out a band-aid PR for this issue.  We should have this merged for the next release planned for 2017.05.31 barring any concerns from Mr @erikquinn

**Comment by Jelmerkeij** [comment]
@indianbhaji @n8rzz Cool! Good work guys.

**Comment by erikquinn** [comment]
No concerns from me! :Smiley:
