### ISSUE TITLE
Late flightstrips at KSEA

### ISSUE THREAD

**Issue by panther2** [openscope/openscope#645]
Browser: Chrome, latest stable, Openscope 5.3.0

Airport: KSEA

Approximate play time before issue: 20 sec

#### Issue Description
Arrivals coming from south-east are represented by a flight strip and commandable only at a very late point:

Here the plane has already entered the scope but is neither clickable nor represented by a filghtstrip:
![os1](https://user-images.githubusercontent.com/20812775/29610179-b5909d16-87f9-11e7-8207-89f0e2919b40.PNG)

It takes to about this point, when the plane gets commandable and is represented by a strip:
![os2](https://user-images.githubusercontent.com/20812775/29610255-edaee09a-87f9-11e7-8d30-74a209e56d09.PNG)

#### Steps to reproduce
Just start the simulation at KSEA and watch incoming flights from SE.

Sorry if I missed something and this is a feature instead of a bug.
In this case a short explanation is appreciated. Thank you :smile:

**Comment by n8rzz** [comment]
That aircraft is likely above the airspace ceiling and only becomes controllable after it has descended into controlled airspace. 

I'd have to check the airport file, but that's my initial guess.

**Comment by erikquinn** [comment]
@panther2 Sure! So that particular aircraft is on the CHINS2 arrival... here's the chart for that:
![image](https://user-images.githubusercontent.com/5103735/29621120-d581fbf8-87ed-11e7-92ef-d3c90670a6c3.png)

Since the wind is out of the south, the sim has the airport in a south flow. Following the instructions for landing south, the aircraft have to cross `AUBRN` at 12000 feet and 250 knots (indicated). Upon passing AUBRN, we can see below that the aircraft has reached the required altitude and speed.
![image](https://user-images.githubusercontent.com/5103735/29621330-703730e6-87ee-11e7-89ab-4bbebbc42a22.png)

So the short answer is that everything is working correctly, and the aircraft are entering approach airspace from the top rather than from the side. This is perfectly common as well.

Hope the explanation helps :smiley:

**Comment by panther2** [comment]
Great, that helps understanding it perfectly. Thanks a lot!
