### ISSUE TITLE
GameOptions not getting stored in localStorage

### ISSUE THREAD

**Issue by scott-j-smith** [openscope/openscope#670]
Browser:  Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)

Airport:  Any

Approximate play time before issue:  Immediate on Launch

#### Issue Description
Launching the 5.4.0 Beta in a new Chrome window (new tab) everything is disabled by default, no matter which airport I start with (cleared the cache to make sure that wasn't part of it).  See screen shot.  Runways & data labels, terrain, restricted areas, routes, etc. all off.   

![image](https://user-images.githubusercontent.com/22403776/29902603-144bc9c4-8dcd-11e7-8595-5e5e75bcaae5.png)

#### Steps to reproduce
- Open browser, launch game in a new tab
- Turn on any options for any airport (e.g. fix and runway labels)
- Close tab, then launch again in a new tab
- Options will be off again

**Comment by sam-irl** [comment]
@erikquinn I have no idea what anything does to be honest, but could (this)[https://github.com/openscope/openscope/pull/663/files#diff-ebddcae30e51af4afeae5f8ab72cdfbeL282] be related?

**Comment by erikquinn** [comment]
@sam-irl Yes, in fact it is. Good find :mag: :wink:

> Launching the 5.4.0 Beta in a new Chrome window (new tab) everything is disabled by default, no matter which airport I start with (cleared the cache to make sure that wasn't part of it). See screen shot. Runways & data labels, terrain, restricted areas, routes, etc. all off.

So the change to defaulting these to _off_ was a design decision, due to the ever-growing clutter factor. If people want the info, it's available, but it's not forced upon them. The core of this issue should be along the lines of the title: the fact that when you refresh, your choices on what to show are not preserved. Personally, I kinda liked it that way; thought it was better to reset basically anew, remembering only which airport to open up... though I suspect I am a minority there. When people undoubtedly say they want their choices preserved upon refresh, we can make sure the `fix labels`, `sid overlay`, `terrain overlay`, and `restricted airspace` are all persistent in browser cache.

:+1: reaction for those in favor of making the options persistent?

**Comment by scott-j-smith** [comment]
Eric,

I am obviously in favor of persistence since I raised the issue.  However, I get where you are coming from regarding the clutter factor.   As a compromise, can we at least make the fix & runway labels persistent?    I could live with turning the SID's, Terrain, and Restricted Airspace on as needed.

Scott

**Comment by n8rzz** [comment]
huh, it appears the code to store `GameOption` values was removed at some point.  We are reading from `localStorage` but never setting to `localStorage`.  The `GameOptions` class went through a little cleanup recently, I must have missed that removal in the PR.

Whoops.

Should be a simple fix.
