### ISSUE TITLE
some minor findings with version 5.4.1

### ISSUE THREAD

**Issue by PetziK** [openscope/openscope#681]
Browser: G-Chrome 64bit, win 7 64bit

Airport: MDSD, several others too

Approximate play time before issue: not relevant

#### Issue Description
1.) when using the arrow feature to handle vertical instructions the up or down arrow is not shown anymore in the command line. instead a void rectangle can be seen. I guess that something went wrong while translating the ascii symbols for the arrows up and down into html (sorry, I am not an expert, but I would start looking for it somewhere there in the code)

2.) at MDSD there is a strange graphic glitch showing a SID Indicator out of place - it got "stuck in the air". It might have happened at other airports too, unfortunately I didn't record and wasn't able to reproduce it

3.) when closing the browser and restarting it and restarting the game almost all settings are gone.
the settings of the settings menu are okay - with exception the design. It always switches back to DEFAULT - (I prefer the classic view)

recommendation:
4.) in default design the contrast of the terrain map is bad - I can not tell the color code of the height of some zones (that is why I prefer the classic setting)

![image](https://user-images.githubusercontent.com/31564099/30067152-4b2dd3a6-925a-11e7-9a87-b83a5fa595d4.png)

![image](https://user-images.githubusercontent.com/31564099/30067246-8d4dfa72-925a-11e7-8780-919ab8b7b652.png)

#### Steps to reproduce
not relevant - restart didn't help nor solve the issue.

**Comment by sam-irl** [comment]
First, obligatory "they're features until proven otherwise".

As for issue 3, the options aren't persistent - see issue #670.

**Comment by Fechulo** [comment]
Regarding issue no. 2: This is definitely a problem with the airport file. @erikquinn could the empty draw sections be causing this?

as for no. 4: I don't like it either, but the colours of the classic theme don't match the blue in the default theme, so we're looking for some other alternative (possibly just a different colour palette)

**Comment by erikquinn** [comment]
Hi @petzik! Thanks for the write-up.

1. Ah yes. That font has been removed and I forgot it was being used here. I did notice a bit ago and didn't write up an issue. This is what I get for that! We can change it to insert the text command instead of the unicode characters since they do not exist in the monoOne font the sim uses.

2. @fechulo has it right I think. I'll have to look, but probably there's something checking like `if (_isEmpty(this.draw))` to determine whether to draw the label and now that the array is 2D this comparison is not happening properly. Most likely an easy fix.

3. Known side effect of a recent change, being dealt with in #670.

4. Yep. We could use a new issue for this since it needs to be addressed.

We will need to break this multi-issue up into individual issues to make tracking work on them easier.

**Comment by PetziK** [comment]
Dear developer folks,
Thank you for your replies. No harm done, I wasn't asking for you to solve those things just right away, instead I wanted to point out some things that caught my eye. Just "clean it up" when you work on the next update, that'l be great!
If the settings are not persistant with every re-logon that is okay - I was just wondering because in the previous version they were. If I have to turn those features on every time I log on it is okay.

I forgot to mention that I like that game / sim a lot and some airports get really really stressful if you don't do the things right. 
The vocal feedback if turned on rocks!
keep going.
Thank you,
OE-PKR over

**Comment by sam-irl** [comment]
1 is in #685 

2 is in #683 

3 is in #670 

4 is in #688 

All new comments should be addressed there.
