### ISSUE TITLE
Method for terrain file generation

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#7]
It is not well-known how to create the GeoJSON files used for terrain data in the sim. See zlsa/atc#278.

I was able to come up with a method that would enable us to create *something*, in zlsa/atc#547, but it has some pitfalls.

Most notably, in cases where the terrain dips *down*, that is not preserved. For example, the south rim of the Grand Canyon has an elevation of about 7,000 feet. The entire grand canyon would be depicted as being 7000 feet. If we stuck a mountain in the middle that rose up above 7000MSL, it would be depicted as being of a higher elevation, but the reduced elevations would not.

For more information on the limitations of our current method, see zlsa/atc#666.

**Comment by Fechulo** [comment]
Recently, I've been playing around with a new method for terrain generation. It's a much easier way of creating a raster file, which replaces GPS Visualizer. First, you'll need to create an account [here](https://urs.earthdata.nasa.gov/users/new?client_id=AISa4KLwyhkdFiqFiH_sXQ&redirect_uri=https%3A%2F%2Fgdex.cr.usgs.gov%2Fath%2Fcallauth.php&response_type=code&state=%2Fgdex%2F). Once you have an account, log in and go the [Global Data Explorer](https://gdex.cr.usgs.gov/gdex/). Then select the desired area using the tools on the top left panel and click on download data:
![selecting](https://user-images.githubusercontent.com/13125311/27054185-02379b3a-4fb8-11e7-931a-030a66d4033a.gif)

Make sure your options match the ones in the following picture and click submit. 
Note: The research area is irrelevant, you can choose any one of those
![submit](https://user-images.githubusercontent.com/13125311/27054233-3024164a-4fb8-11e7-957e-c5e685b82ff4.PNG)

It may take a few minutes and it might time out (more than once), but if you keep trying and remain patient you'll end up with an option to download the GeoTIFF. Press download and while that's happening you can open up QGIS.

Inside QGIS, open up the GeoTIFF as a raster layer:
![raster](https://user-images.githubusercontent.com/13125311/27054859-61856098-4fba-11e7-8c17-18e3ef011f87.gif)
 
And now you can continue the terrain generation process following the usual steps.
**Note: Instead of 'elevation', the GeoTIFF uses 'Band 1' so that's the parameter that should be used when extracting a contour. Once the GeoJSON file is generated, you must replace all instances of 'Band 1' with 'elevation' so Openscope can interpret it correctly.**

The main issue with this method (other than the frustrating GoeTIFF generation) is that it's very detailed, maybe _a bit too detailed_, but the results definitely look a lot better than using the current method:
![terrain](https://user-images.githubusercontent.com/13125311/27055043-ff8c12c8-4fba-11e7-8c11-c76bb8a6ab75.PNG)

**Comment by erikquinn** [comment]
Some notes from a few weeks ago of an improved (old) methodology. When we come back to this, a combination of the new data sourcing and techniques below would be helpful when it comes to documenting the process of generating terrain...

```
Import perimeter from wkt: `POLYGON((lon lat, lon lat, ...))`
Create perimeter buffer ("perimeterBuffer.shp"):
    vector --> geoprocessing --> buffer (buffer distance 0.4)
Create point grid ("points.shp"):
    vector --> research --> regular points (perimeterBuffer, spacing 0.02)
Save points to geoJSON ("points.geojson"):
    right click layer --> save as --> geoJSON (default settings)
Convert geoJSON to `latitude,longitude` txt ("txt/points.txt")
Use GPSVisualizer to get elevations
Reformat and save result to `latitude,longitude,elevation` txt "txt/elevationData.txt"
Import elevation data from "txt/elevationData.txt"
Create raster ("raster.tif")
    Processing --> Toolbox --> SAGA --> Raster Creation --> Natural Neighbor (extent:perimeterBuffer, units:0.0005)
Create contour ("contour" folder)
    Raster --> Extraction --> Contour (interval: 304.8, attribute name: `elevation`)
Convert contour to polygons ("contour/contourPoly.shp")
    Vector --> Geometry --> Lines to Polygons (layer:contour)
Set bottom-up feature rendering
    Right click layer --> Properties --> Style --> Layer Rendering --> Control Feature Rendering Order --> elevation (ascending)
Edit polygons with node tool to remain outside of perimeter
Clip terrain poly to perimeter ("terrain.shp")
    Vector --> Geoprocessing --> Clip (contourPoly to perimeter)
Save terrain geoJSON ("terrain.geojson")
    Right click layer --> save as (`COORDINATE_PRECISION: 7`)
```

**Comment by tedrek** [comment]
Another source of DEM data is https://earthexplorer.usgs.gov/, the void filled Shuttle Radar Topography Mission (SRTM) data at 3 arc seconds is a pretty good fit for our needs and covers much of the populated world.  The multiple tiles can easily be handled with building a virtual raster layer in QGIS from the Raster menu.

Here are my notes for a different method once the DEM data has been imported.  The principle is to clip the contours at a point slightly larger than the desired end product, create a line in the same layer as the contours at the desired border, create polygons from the resulting set of lines via the Processing Toolbox, and finally re-associate the correct elevation with the polygons.  The elevation isn't always correct yet, and there are holes in the polygons which should be filled.  Unfortunately I'm out of time for the moment.

> create Contours
> Select contours with elevation = 0 and delete
> Rectangles Ovals digitizing plugin
> Create circle
> clip contours with circle
> Multi-part to single part clipped
> Buffer circle 0.005
> Polygon to line Buffered Circle
> Merge Single part clipped and Line of Buffered circle
> Toolbox->QGIS->Vector geometry->Polygonize on Merged layer
> Enable zonal statistics plugin, run on Lines to polygons layer for median DEM value (should probably be average)
> Select "median" < 304.8 and delete
> Select $area < 0.00005 and delete
> Add elevation virtual field: to_int("median"/304.8) * 304.8

**Comment by tedrek** [comment]
Instead of deleting by area, first use the eliminate sliver polygons tool to merge small polygons by area with their neighbours.

**Comment by georgeenciu** [comment]
@tedrek worked like a charm, thank you!

**Comment by Fechulo** [comment]
@tedrek I followed all the steps and I'm honestly amazed by the results. Looks awesome!
Here's a comparison of the old method and @tedrek's method:

Old Method:
![old](https://user-images.githubusercontent.com/13125311/29499584-972ca0ca-860c-11e7-80c7-907bdfbdab65.PNG)
New Method:
![new](https://user-images.githubusercontent.com/13125311/29499586-9ce05110-860c-11e7-97d4-826f9c179e9d.PNG)

I mean, the pictures say it all...

**Comment by erikquinn** [comment]
holy :hankey:! That's awesome :smiley:

Any noticeable difference when panning as far as lagginess? And what's the difference in file size?

**Comment by Fechulo** [comment]
It's a bit slower than before, nothing too serious though. It could be simplified further if needed.

The original terrain file was 57 KB while the new one is 668KB (Almost 12 times larger)

**Comment by erikquinn** [comment]
If it's not too sluggish, it might be okay, though that is a much larger download, espcially considering the eventuality of a large library of airports for somebody with a slow connection. Nonetheless, this is a big step up in quality so :shipit:

It is probably worth looking into if we can add a small degree of "simplify polygons" somewhere in that process; I wouldn't be surprised if we could quarter (or more) the file size without any perceivable difference in resolution.

**Comment by Fechulo** [comment]
For the image above I simplified the contour using tolerance 0.0005 (same as we were using before) but I was already struggling with the new method and didn't want to mess around with anything else 😄

**Comment by tedrek** [comment]
I messed around with simplifying geometries, a tolerance of 0.002 results in the following:

![kpdx-simplify-0d002](https://user-images.githubusercontent.com/386829/29506979-01e974e2-8603-11e7-941c-2f61d373ec34.png)

The file size is now 253k and from my point of view the quality is roughly the same.  I played with various other tolerances, depending on the particular terrain it can take going higher (say 0.005) if there is a lot of already pretty smooth lines.  This was the best I got in terms of quality to file size.

I've modified the earlier script to specify a simplify step
```quinnScript
Vector->Geometry tools->Simplify geometries
  Input layer: contours
  Tolerance: 0.002
  Click Run

Remove contours layer
Rename Simplified layer to contours
```

**Comment by n8rzz** [comment]
One other thing to keep in mind here is that we are currently using only **_one_** canvas.  That means that **_everything_** gets re-drawn every frame (up to 60 times per second).  

Once we split this up into multiple canvases (starting with #236), we should see a bump in performance.  I'm hopeful it will actually be a large bump.  Re-drawing terrain every frame is very costly and refactoring to only draw on view change should make a big difference.

**Comment by erikquinn** [comment]
Now we're talking! That's almost a 65% reduction in download size and they look the same to me. That ought to be enough. And @n8rzz you have a point... once we stop redrawing the entirety of the canvas every single frame, the complexity of the background will not affect the performance of the aircraft position calculations because it's only being redrawn if the canvas is panned.

I think we actually have an answer here! If we can get this into the documentation on a `documentation/7` branch with a PR, I think we can finally move on from this! Huzzah! :tada:

**Comment by tedrek** [comment]
I'll create a pull request in the next day or two.

Regarding drawing performance see my notes in #236
