### ISSUE TITLE
simulator fails to load

### ISSUE THREAD

**Issue by jean1689** [openscope/openscope#702]
Browser: google crome internet explorer 

Airport: no

Approximate play time before issue:
I can not enter the simulator, it remains frozen in the initial interface
as the image shows

Thanks for the help

#### Issue Description
_please include any console errors and/or screenshots_ 
![fefff](https://user-images.githubusercontent.com/31263156/30409775-c54ed950-98cc-11e7-9600-0aa7161936e9.jpg)

#### Steps to reproduce
-

**Comment by n8rzz** [comment]
Hi @jean1689!  Thanks for your bug report.  Could you try hitting out development server  (http://openscope-dev.herokuapp.com) and see if you have the same issue.

Also, with Chrome, could you take a look at the `console` tab within devtools (`ctrl` + `shift` + `i`) and report any red errors you see there.

**Comment by jean1689** [comment]
with the new web address if I can enter the simulator http://openscope-dev.herokuapp.com/
what could be going on?

**Comment by erikquinn** [comment]
Might be a case of the active airport not existing anymore. If so, maybe we can do a check to see if the airport in local storage exists in the load list, and if not, then reset todl the default airport?

**Comment by jean1689** [comment]
when the simulator starts, the start airport is KSEA in version beta

**Comment by erikquinn** [comment]
@jean1689 sorry for the delay. Glad to hear it works on the dev site; that's probably just because you don't have that one in your browser cache. At the very least, I'm 90% confident you can resolve the issue on the normal site if you clear that cache. Here is the full process for that in Google Chrome:

1. Go to [www.openscope.co](http://www.openscope.co).
1. Press F12 (or `Ctrl + Shift + I`) to open the developer tools.
1. Let us know if there are any red errors in the console tab, for our research into the issue.
1. In the application tab, go to "Clear Storage" on the left, then click the "Clear Site Data" button.
1. Refresh and enjoy :smiley:

And we'll look at some ways to prevent this from being possible, so our users don't have to go through this process.

**Comment by erikquinn** [comment]
Created #709 to hopefully prevent other users from having to deal with this issue.

**Comment by jean1689** [comment]
WITH THIS THE PROBLEM WAS RESOLVED THANK YOU VERY MUCH

2017-09-19 10:59 GMT-05:00 Erik Quinn <notifications@github.com>:

**Comment by erikquinn** [comment]
You're quite welcome. :smiley:

Closing!
