### ISSUE TITLE
Disallow selection of aircraft who cannot receive instructions

### ISSUE THREAD

**Issue by sam-irl** [openscope/openscope#818]
When an aircraft is outside of our radar coverage, it is able to be selected, and the aircraft's callsign is populated in the command bar. However, since the aircraft has not yet entered our airspace, there is no flight strip on them, nor will they respond to any of our commands.

_To prevent users from not realizing the aircraft is not yet controllable, do not allow the aircraft to appear "selected", either in the command bar, or with the enlarged target dot._
![image](https://user-images.githubusercontent.com/29643177/32329769-faa3ff80-bfab-11e7-8c93-8291a8a6461f.png)

**Comment by erikquinn** [comment]
So _part_ of this is intended, and part of it is perhaps able to be done better.

It used to be that only aircraft _within_ our airspace could be controllable in any regard, and now we are able to manipulate the _data block_ in certain ways (and not in others), as well as selecting it. While the aircraft is not under our control, it simply _ignores_ any instructions we give to it because it is pretending to "not be on our frequency".

The potential issue I see with that is the obvious one that we may not notice an aircraft is not quite in our airspace (especially as we implement stratified airspaces with many altitude layers), and issue them a command, and not notice that they did not respond. Perhaps we could add a red response about the aircraft not being controllable to alert the controller that the aircraft will not hear you, but I have mixed feelings on that myself.

Open to thoughts from anybody on any changes in this realm!

**Comment by indianbhaji** [comment]
It depends on how you would want it since realistically if an aircraft is not on your frequency, and you call them, you get no response. I would go for the latter.

**Comment by erikquinn** [comment]
@openscope/simulator-collaborators Anybody have input on this issue? Should it be closed? Should we change something to better alert the user to the fact that their command was not heard?

**Comment by scott-j-smith** [comment]
Is it possible to prevent the call sign from showing up in the command area, thus the controller should realize that commands cannot be issued?  If not, then I'd vote for at least the red warning text you mentioned.   It would be a nice enhancement for the voice synthesizer to read out those messages though (currently they are ignored).  I sometimes miss warning messages in red text because I'm focused on the scope display and listening to the audio voice readback.

**Comment by jakcharvat** [comment]
Maybe show the AC itself in red, or disable the command line when the AC is
selected.

**Comment by erikquinn** [comment]
Okay, then let's prevent selection of the aircraft until it is controllable. That sounds like a good solution to me, and since it would only affect the pseudopilot, it is a perfectly reasonable thing to do in terms of realism as well.

Edited the labels and issue description accordingly, and filed away in zube! 😄

**Comment by n8rzz** [comment]
Give #902 a shot (scroll down to the review app).  This is a very quick and dirty solution, but I think it easily addresses the original concern here.

I'm open to suggestions on my solution, though.

**Comment by n8rzz** [comment]
Updates from openscope/openscope#906  may cause some conflicts.  verify usage of `inside_ctr` has been properly updated.
