### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by binaryfunt** [openscope/openscope#871]
Browser: Chrome

Airport: KATL

Approximate play time before issue: 40 mins (may depend on RAM)

#### Issue Description
After 40 mins of play, the RAM usage of Openscope gradually rises to 4GB (out of 8GB) while the gameplay slows slightly, then Chrome crashes (`Aw, snap!`). Worst for Hartsfield-Jackson Atlanta International I think because the traffic is so heavy. I didn't see any errors in the console up to the point of crashing.

**Comment by n8rzz** [comment]
I feel like this is a two part problem:  The first part is going to be solved by this PR: https://github.com/openscope/openscope/pull/869.  The second part is really whatever is left over from that PR.  I big part of the RAM usage is due to how the `StripView` was implemented (shame on me).  The PR resolves that part of it and improves that heap size by quite a bit.  

We have some other issues out there to address performance type things: #232, #42, #314 plus more I'm sure.

**Comment by erikquinn** [comment]
Will reexamine this after merging #869, since it's quite likely performance at atlanta will drastically improve once #837 is resolved.

**Comment by erikquinn** [comment]
Manually verified before and after on #869, and can confirm this is definitely resolved. A very big difference!

Closing.
