### ISSUE TITLE
Projected Path not showing when time warp is enable

### ISSUE THREAD

**Issue by MartinW2002** [openscope/openscope#920]
Browser: Chrome

Airport: Frankfurty

Approximate play time before issue: a few hours

#### Issue Description
When clicking on time warp the projected paths no longer get displayed.

**Comment by n8rzz** [comment]
This is by design. Currently the way the projected paths are done is incredibly non-performant at  normal speeds. At timewarp things are unplayable. 

In the future we plan to make this better, but there is also the realism argument. If you’re a real controller you wouldn’t have access to a projected path only the previous path.

**Comment by MartinW2002** [comment]
But as a real controller you see in what direction each heading is. I'm not always sure what the heading should be exactly and by looking if the path isn't where I want it to be I can correct it accordingly.

**Comment by erikquinn** [comment]
@MartinW2002 You're right, _those_ are realistic, and those remain available. In settings, just turn on PTLs to the desired length. What this issue is about is the red lines which reflect physics and avionics updates to run the simulation of the aircraft into the future and draw a line where it ended up, which obviously is not possible in real life. So the _red projection lines_ will eventually be removed altogether, but the _PTLs_ are available now, and will remain available.

So really the only thing lost here is the ability to see where the filed route goes, and we have plans for dealing with that in #119 and #828.

**Comment by MartinW2002** [comment]
@erikquinn You can see which heading you have sent the plane to once it has turned completely, but I can't tell whether I want him to go 220 or 235. And that's why those red lines help because then you can immediatly see where you send the plane. As a real controller you don't type the heading but click it and when hovering you see where the airplane would go if it were on that heading.

**Comment by MartinW2002** [comment]
@erikquinn Why would it not be possible to simulate the trajectory of the airplane? Modern upper airspace control centra have shown the airplane's trajectory for 15 years.

**Comment by erikquinn** [comment]
> You can see which heading you have sent the plane to once it has turned completely, but I can't tell whether I want him to go 220 or 235.

Yup, and that's part of the challenge of real life.

> As a real controller you don't type the heading but click it and when hovering you see where the airplane would go if it were on that heading.

I assume this is on some sort of european system, I haven't heard of it working quite like that. In the US, this is done via a keyboard command (dependent upon whether its a ERAM/STARS/etc scope) and clicking rather than hovering, but basically the same idea. That is a planned enhancement (see #45).

> Why would it not be possible to simulate the trajectory of the airplane? Modern European upper airspace control centra have shown the airplane's trajectory for 15 years.

They cannot predict the trajectory in the same way as the red line is generated. The red line is only created by the fact that the simulator _itself_ turns all the aircraft, so it knows exactly how and when each maneuver will be conducted, and it simulates into the future. Therefore, the red projection line is not an _approximation_ like we would really have access to in real life, it is _the exact_ course the aircraft will take. Though this is a simulator, and we _could_ give users that information, we always prefer to give users the closest equivalent to the real-world situation, and displaying the red line is a significant deviation from that goal.

I am not familiar with how advanced the trajectory projection logic is for whatever system eurocontrol may be using, but I seriously doubt it would do anything more than maybe adding some curvature along its flightplan route appropriate for the aircraft's speed, to approximate the path the aircraft will take when it cuts corners between high-angular-difference waypoints. Again, I should emphasize that it could only ever project what the airplane is _assigned_ to do, which is not necessarily what the airplane _will_ do. For example, if they're en route on their flight plan route, and they're given a vector, and that vector is not entered into the system, the scope will not predict that turn. If it _is_ entered, maybe it will. But the difference here is that the red line shows what _will_ happen, and much of that information is never available to the controller on their radar display (such as localizer interception).

If you can provide more detail on how their projection system works (and provide a reliable source to verify that information), we can consider adding a simulation of _that_ behavior, but we will not be continuing with the current red line projection because of the fundamental way we made it work, in short because it simply "knows too much".

**Comment by n8rzz** [comment]
It’s not that it isn’t possible, it totally is. It’s that with our current architecture it’s just not feasible. We lock projected trajectories to only 1x because it takes a lot of time and resources to calculate that path. 

As the timewarp increases so does the calculation complexity. At high timewarps with projected paths, it will actually crash the browser. We made the compromise to support it only at 1x. But even so, as Erik mentioned, we do have PTLs.

**Comment by MartinW2002** [comment]
@erikquinn @n8rzz 
Why don't you remove everything that a real system wouldn't know from the red line? This would make it more realistic and easier to compute. 

What does the browser know when computing the red line that a real system wouldn't know? The route, heading, speed and altitude is all known by the real system.

I could explain Eurocontrol's system further, but is this the right place to explain that or should I start a new thread or something?

**Comment by erikquinn** [comment]
It's kinda an issue of how it works. It currently just pauses the sim, makes copies of every airplane which are run in fast forward for like 20 minutes of game time, saving each aircrafts position along the way. Then those positions are drawn in red. Each new frame (60 per second), this process repeats. So basically it's like running 50 times the logic just to draw the red lines, which explains why it's so slow.

Because it's literally just allowing the simulator itself to run, instead of using projection methods similar to ones that may be used in real life, it isn't really a matter of removing the stuff it shouldn't show. It involves a fresh rewrite of all the projection logic to do anything other than what it does right now. And due to the lack of priority, it's unlikely that would get any attention for quite a while.

And regarding eurocontrol scopes, actually [slack](http://slack.openscope.co) would be a great place for that, in the `#ideas` channel to start. That's where we all converse about suggestions like these. :smile:

**Comment by MartinW2002** [comment]
@erikquinn Ok. I'll check out slack and if I have some time, I might try to make the projection logic.
