### ISSUE TITLE
Wiki vs In-Repo Documentation

### ISSUE THREAD

**Issue by erikquinn** [openscope/openscope#958]
In light of #956, we need to address the fact that we have essentially two different sources of documentation, which I know better then anybody (please don't ask :laughing:) is never a good idea; you always want exactly one source of truth.

I propose the wiki be obliterated and replaced with a simple link to the documentation home page, that way anybody who visits the wiki will always be directed to the most accurate and up to date information. Am open to doing this other ways, perhaps there is some fancy-people way to get the wiki to populate based on *.md files from our documentation directory, but that would be for extra points. All we really need is to remove the duplicity.

**Comment by n8rzz** [comment]
Completely agree

**Comment by cake-pie** [comment]
Perhaps a lesser known fact about GitHub wikis <sub>(and also gists!)</sub> is that under the hood it is simply a separate repo (distinct from the main one) that can be cloned, have its contents edited, and the changes committed and pushed. [Quick overview](https://gist.github.com/subfuzion/0d3f19c4f780a7d75ba2).

It doesn't support issues and PRs though, so the current system of having a documentation folder within the main repo does give benefits of being able to use those features to discuss and collaborate on the docu.

> I propose the wiki be obliterated and replaced with a simple link to the documentation home page, that way anybody who visits the wiki will always be directed to the most accurate and up to date information. 

Rather than "obliterating" the wiki, it can be set up to behave as the "deployed" copy of the documentation.

> Am open to doing this other ways, perhaps there is some fancy-people way to get the wiki to populate based on *.md files from our documentation directory, 

Actually not hard at all, once you understand the implications of the wiki being a repo.
So, apart from having a local clone of the main repo, just have a separate clone of the wiki repo.
Then, as part of the release workflow when a new version of the app gets built and deployed, also do:
- sync wiki repo with main repo docu folder (delete-and-replace)
- commit changes and push.

If you want, there are tools out there to do this, e.g. [gödel](https://github.com/palantir/godel) tool has [this feature](https://github.com/palantir/godel/wiki/GitHub-wiki) and they use it themselves to have their ["GitHub Wiki mirrors the contents of the `docs` directory"](https://github.com/palantir/godel/blob/master/README.md#documentation). Though might be overkill to use it just for one little feature.

**Comment by erikquinn** [comment]
This has been implemented as proposed, closing.
